language: python
cache: pip
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip3 install mypy types-cachetools -r requirements-dev.txt
before_script:
  - pip3 freeze
script:
  - python3 -m unittest test

